import { type z } from "zod";
import { type AiSchema } from "../routers/_app";

export default async function generateDescription(attributes: z.infer<typeof AiSchema>): Promise<string> {
    console.log(attributes);
    await new Promise((resolve) => setTimeout(resolve, 1000));

    return 'This is a description generated by Google Generative AI.'
}
